# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-13 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_delete_userlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(default='123456', max_length=32)),
                ('email', models.CharField(max_length=32)),
            ],
        ),
    ]
